### ISSUE TITLE
down() doesn't revert failed up()

### ISSUE THREAD

**Issue by zatziky** [tj/node-migrate#120]
Let's say you have 2 migrations:
- migration-a.js (migrated successfully)
- migration-b.js 

When `migration-b` fails in `up()` and you try to recover state calling `set.down('migration-a')` then you revert changes from `migration-a`. If you try to exececute `set.down('migration-a')` then `down()` is **not** called.

I believe that `down()` shall correct errors after an unsuccessful `up()` from the same file. Is there a way how to achieve it or do we have to implement it?

**Comment by wesleytodd** [comment]
Hey @zatziky.  I don't think I fully understand your scenario.  If the tool failed in `migration-b` then it will not attempt to run `down()` on `migration-b` because it did not successfully run `up()` and assumes no changes were made.  `down()` does not correct errors, it reverses the changes made in `up()`.

If you write a migration that can be partially applied and then fail, you can get yourself in a problematic state.  If it is a traditional relational database you might try wrapping your migrations in a transaction.  In other systems it might be more difficult, but either way this tool cannot solve for all of these cases and it is up to you depending on how you use it.

Does that answer your question?

**Comment by zatziky** [comment]
Hello @wesleytodd, you explained it well. I wanted to revert changes of `up()` in `down()`. As I understand the correct purpose now I'm closing the issue.
