### ISSUE TITLE
Promise resolving to truthy is treated as rejection

### ISSUE THREAD

**Issue by gpinhey** [tj/node-migrate#133]
https://github.com/tj/node-migrate/blob/93dfb65e3605e7f2b4298db7e06523a5ee2438aa/lib/migrate.js#L47-L51

Be careful when mixing promises and callbacks. This passes a node-style callback as a `.then()` handler to a promise, meaning that the resolved value of the promise is the first argument of the callback, indicating to the callback that there was an error if the resolved value of the promise is truthy.

This should probably read `.then(() => completeMigration(null))` since `completeMigration()` only cares about whether it was passed an `err` argument.

**Comment by wesleytodd** [comment]
Hey @gpinhey.  I think this is a reasonable change.  If you want to submit the PR I would accept it.

I think the reason this has been acceptable to most people so far is because they are not resolving their promises with a value, so typically it is just `undefined`.  But since the library should be ignoring it, this change makes it more explicit and removes the odd behavior when you do resolve with something.

**Comment by wesleytodd** [comment]
Closing because the PR is open.  #135 134
