### ISSUE TITLE
Release with TS typings?

### ISSUE THREAD

**Issue by qqilihq** [tj/node-migrate#186]
There's [TS types](https://github.com/tj/node-migrate/commit/18f5ad0af8e49d7e8e12335590b30740348f00d9) available in the `main` branch, but unfortunately not via NPM. 

Could you push this to NPM?

**Comment by carnesen** [comment]
At this point a year and a half after the types were merged in this repo and a year after this issue was filed, it would appear that a new release including the types is not forthcoming. I'd say the best path forward would be to publish the type definitions as @types/migrate in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) and to avoid further confusion, submit an MR to this repo to remove the types.

**Comment by wesleytodd** [comment]
I can publish. Sorry I must have missed that, IIRC I had ping'd a few other PRs in the hopes of getting them merged.  Will do it now.

**Comment by wesleytodd** [comment]
ok, published and I did some of the easy dep updates while I was at it. I at least got the dep updates which removed the silly npm audit reports for old mocha (which are all not "real" in that they do not effect any test scenario).

`npm i migrate@1.8.0`
