### ISSUE TITLE
Removing old migrations causes confusion

### ISSUE THREAD

**Issue by qqilihq** [tj/node-migrate#89]
Removing old migration files seems to bring node-migrate out of sync. Example:

```
$ migrate create one
$ migrate create two
$ migrate create three
$ ls migrations
1510670884434-one.js   1510670888566-two.js   1510670890981-three.js
$ migrate
  up : 1510670884434-one.js
  up : 1510670888566-two.js
  up : 1510670890981-three.js
  migration : complete
```

Later we add a new migration and remove old ones, which we do not want to support any longer:

```
$ migrate create four
$ ls migrations
1510670884434-one.js   1510670888566-two.js   1510670890981-three.js 1510670980407-four.js
$ rm migrations/1510670884434-one.js migrations/1510670888566-two.js
$ ls migrations
1510670890981-three.js 1510670980407-four.js
$ migrate
  migration : complete
```

Notice that `1510670980407-four.js` will **not get executed** now.

In our case, we would like to remove old migration scripts, because their logic wouldn't work any longer anyways due to changed dependencies, etc.

This happens with 0.2.4 and the version from the `next` tag as well. Is this behavior intentional or could be handled more gracefully in the future?

**Comment by wesleytodd** [comment]
Hey @qqilihq!  The `next` branch should not exhibit this behavior, it tracks migrations by name and should run your fourth migration but warn you that something is missing.  If you can create a POC or a test case using the `1.x` branch I can take a look.

That being said, removing migrations is not a supported use case, and it is something I would advise against.  The goal of this tool is to track persistence layer changes in a linear fashion.  What we have done in the past is create "rollup" migrations as a start of a new migration chain which bundles all previous migrations state into a single new migration, then build up again from there.  But when we do that it invalidates all the previous state, so would require some orchestration depending on the structure of your project/team, thus advising against.

If you have an example of a different tool that has a feature to remove migrations, could you point it out to me?  Because maybe I am just not seeing the use case for it and can be "enlightened" :)

**Comment by wesleytodd** [comment]
An example of some of the cli integration tests: https://github.com/tj/node-migrate/blob/1.x/test/integration.js

In case you want to do a PR that just shows the issue.

**Comment by qqilihq** [comment]
Hi @wesleytodd! Thanks for the detailed feedback.

I'm currently a little stuffed with work, but I'll double check wether the given case covers my issue, many thanks! I'll get back about that asap.

I understand that my given scenario is quite “special”. Let me highlight our use case anyways: We’ve built a product in a quite “agile” manner. Means, at the beginning we did many DB migrations and never cared about covering the ”back” path (ie. our `down` implementation just throws an `Error` 😊 ). That’s probably a terrible abuse of the initial idea behind `node-migrate`, but the tool worked quite well for us and we wouldn’t want to miss it.

That being said, we’ve now reached a point where the child has become an adult, and our migrations will become more sparse (and now also cover potential back migrations). That’s why I thought a “clean cut” would be nice.

That being said, I've just realized that we can simply remove all old the old migration steps from our repo, delete the state file and start with over. Problem solved, simple.

Still, at the end, I think either logging a warning or even throwing an error in the above highlighted case would be best -- it avoids any misunderstandings concerning the usage of `node-migrate`.

Looking forward to v1.0. Many thanks for your efforts!

**Comment by wesleytodd** [comment]
I think your use case makes sense, but I still am not sure how we would want to move forward with support for this.  My first idea is a command like `migrate clean` which would reset the state based only on what is in the migrations file tree.  So it would maintain the run status, but mark the missing ones so that it does not error/warn.  Seem reasonable?

**Comment by kidnme** [comment]
I have a similar issue, but a somewhat different use case.  So, I thought I'd mention it here and you can decide whether to just squelch it, answer it, or create a new issue.

I also only ever perform up migrations (stubbed down migrations to effectively do nothing) and I only perform them INSIDE my node application (so they are NEVER run using the command line interface).  So, when my node application starts, it initializes the database (nedb btw), then runs migrations, and finally starts the rest of the application.  There is also a use case where my application has to "rerun" all or some portion of the migrations again.  We have a backup/restore operation that saves the state of the migrations in the backup and runs the missing ones on any restore (including very old backups that don't even have the migrations saved in them).  Lastly, I'm running on an embedded device and startup/init time and memory footprint is kind of important.

With that in mind, I'd like to not even load any migration file that has already run according to the saved migration state. Trying to cleverly filter files out with the filter function produces the error that a migration is missing (because it exists in the saved migration state).

So, I have some thoughts here, but I thought I'd first get this comment out and we can go from there.  Also, I have some other issues/enhancements that might be useful, but I'll leave those for later.

**Comment by wesleytodd** [comment]
Just cleaning up old issues, and this should be resolved in the current major version.  Feel free to reopen if there is more to discuss or resolve.
